; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Mon programme test"
#define MyAppVersion "1.0"
#define MyAppPublisher "Pyxis team"
#define MyAppExeName "test.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{39CFDB45-2FD3-4B94-9B4B-8B6873DA3D5E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputDir=C:\Users\SIMFRA\Desktop\ProjetsC
OutputBaseFilename=setup
SetupIconFile=C:\Users\SIMFRA\Desktop\ProjetsC\Publication\pyxis.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\test.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\freetype6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\gtkrc"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\image1.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\intl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libasprintf-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libatk-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libcairo-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libcairo-gobject-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libcairo-script-interpreter-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libexpat-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libfontconfig-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libgailutil-18.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libgcc_s_dw2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libgdk_pixbuf-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libgdk-win32-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libgio-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libglib-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libgmodule-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libgobject-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libgthread-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libgtk-win32-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libpango-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libpangocairo-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libpangoft2-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libpangowin32-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\libpng14-14.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\pyxis.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\test.glade"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\SIMFRA\Desktop\ProjetsC\Publication\themes folder\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

